app/models/reviewer.py
from app import db


class Reviewer(db.Model):
  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), unique=True, nullable=False)
  topic_id = db.Column(db.Integer, db.ForeignKey('topic.id', ondelete='SET NULL'), unique=False, nullable=True)
  journal_log = db.relationship('JournalLog', backref='reviewer', lazy=True)
  topic = db.relationship('Topic', back_populates='reviewer', lazy=True)

  def __repr__(self):
    return '<Reviewer %r>' % self.user_id
  
  def create(self, user_id, topic_id):
    reviewer = Reviewer(
      user_id=user_id,
      topic_id=topic_id
    )

    db.session.add(reviewer)
    db.session.commit()

  def update(self, user_id, topic_id):
    reviewer = Reviewer.query.filter_by(user_id=user_id).first()
    reviewer.topic_id = topic_id

    db.session.commit()
  

app/routes/admin.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required
from app.middlewares.role_checker import RoleChecker
from app.controllers.topic import TopicController
from app.controllers.journal import JournalController
from app.controllers.user import UserController
from app.controllers.applicant import ApplicantController


admin = Blueprint('admin', __name__, template_folder='templates')
role_checker = RoleChecker()

topic_controller = TopicController()
user_controller = UserController()
journal_controller = JournalController()
applicant_controller = ApplicantController()

@admin.route('/', methods=['GET'])
@login_required
@role_checker.check_permission(role='admin')
def index():
  metrics = {
    'topic': len(topic_controller.topic.query.all()),
    'manuscript': len(journal_controller.fetch_by_status(status='Submitted')),
    'published': len(journal_controller.fetch_by_status(status='Published')),
    'applicant': len(applicant_controller.fetch_all())
  }
  return render_template('pages/admin/index.html', metrics=metrics, role='Admin')


@admin.route('/topic', methods=['GET'])
@login_required
@role_checker.check_permission(role='admin')
def view_topic():
  topics = topic_controller.fetch_all()
  return render_template('pages/admin/topic/view.html', topics=topics, role='Admin')


@admin.route('/topic/create', methods=['POST'])
@login_required
@role_checker.check_permission(role='admin')
def create_topic():
  topic_controller.create(request=request.form)
  return redirect(url_for('admin.view_topic'))


@admin.route('/topic/update/<int:id>', methods=['POST'])
@login_required
@role_checker.check_permission(role='admin')
def update_topic(id):
  topic_controller.update(request=request.form, topic_id=id)
  return redirect(url_for('admin.view_topic'))


@admin.route('/topic/delete/<int:id>', methods=['GET'])
@login_required
@role_checker.check_permission(role='admin')
def delete_topic(id):
  topic_controller.delete(topic_id=id)
  return redirect(url_for('admin.view_topic'))

@admin.route('/user', methods=['GET'])
@login_required
@role_checker.check_permission(role='admin')
def view_admin():
  admins = user_controller.fetch_user_by_role(role='admin')
  return render_template('/pages/admin/admin/view.html', admins=admins, role='Admin')


@admin.route('/user/create', methods=['POST'])
@login_required
@role_checker.check_permission(role='admin')
def create_admin():
  user_controller.create(request=request.form, role='admin')
  return redirect(url_for('admin.view_admin'))


@admin.route('/user/update/<int:id>', methods=['POST'])
@login_required
@role_checker.check_permission(role='admin')
def update_admin(id):
  user_controller.update(request=request.form, user_id=id)
  return redirect(url_for('admin.view_admin'))


@admin.route('/user/delete/<int:id>', methods=['GET'])
@login_required
@role_checker.check_permission(role='admin')
def delete_admin(id):
  user_controller.delete(user_id=id)
  return redirect(url_for('admin.view_admin'))


@admin.route('/reviewer', methods=['GET'])
@login_required
@role_checker.check_permission(role='admin')
def view_reviewer():
  reviewers = user_controller.fetch_user_by_role(role='reviewer')
  topics = topic_controller.fetch_all()
  return render_template('/pages/admin/reviewer/view.html', reviewers=reviewers, role='Admin', topics=topics)


@admin.route('/reviewer/create', methods=['POST'])
@login_required
@role_checker.check_permission(role='admin')
def create_reviewer():
  user_controller.create(request=request.form, role='reviewer')
  return redirect(url_for('admin.view_reviewer'))


@admin.route('/reviewer/update/<int:id>', methods=['POST'])
@login_required
@role_checker.check_permission(role='admin')
def update_reviewer(id):
  user_controller.update(request=request.form, user_id=id)
  return redirect(url_for('admin.view_reviewer'))


@admin.route('/reviewer/delete/<int:id>', methods=['GET'])
@login_required
@role_checker.check_permission(role='admin')
def delete_reviewer(id):
  user_controller.delete(user_id=id)
  return redirect(url_for('admin.view_reviewer'))


@admin.route('/applicant/', methods=['GET'])
@login_required
@role_checker.check_permission(role='admin')
def view_applicant():
  applicants = applicant_controller.fetch_all()
  return render_template('pages/admin/applicant/view.html', role='Admin', applicants=applicants)


@admin.route('/applicant/download/<filename>', methods=['GET'])
@login_required
@role_checker.check_permission(role='admin')
def cv_download(filename):
  return applicant_controller.cv_download(filename)


@admin.route('/applicant/receive', methods=['POST'])
@login_required
@role_checker.check_permission(role='admin')
def receive_applicant():
  applicant_controller.receive(request=request.form)
  return redirect(url_for('admin.view_applicant'))


@admin.route('/applicant/reject', methods=['POST'])
@login_required
@role_checker.check_permission(role='admin')
def reject_applicant():
  applicant_controller.reject(request=request.form)
  return redirect(url_for('admin.view_applicant'))

app/routes/reviewer.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from app.controllers.auth import AuthController
from app.controllers.journal import JournalController
from app.controllers.topic import TopicController
from app.middlewares.role_checker import RoleChecker


reviewer = Blueprint('reviewer', __name__, template_folder='templates')
role_checker = RoleChecker()
journal_controller = JournalController()
topic_controller = TopicController()

@reviewer.route('/', methods=['GET'])
@login_required
@role_checker.check_permission(role='reviewer')
def index():
  return redirect(url_for('base.view_publication'))


@reviewer.route('/manuscript/submission', methods=['GET'])
@login_required
@role_checker.check_permission(role='reviewer')
def manuscript_submission():
  manuscripts = journal_controller.fetch_by_status(status='Submitted')
  topics = topic_controller.fetch_all()
  return render_template('pages/reviewer/manuscript/submission.html', role='Reviewer', manuscripts=manuscripts, topics=topics)


@reviewer.route('/manuscript/download/<filename>', methods=['GET'])
@login_required
@role_checker.check_permission(role='reviewer')
def manuscript_download(filename):
  return journal_controller.download(filename)


@reviewer.route('/manuscript/detail/<id>', methods=['GET', 'POST'])
@login_required
@role_checker.check_permission(role='reviewer')
def manuscript_view_detail(id):
  manuscript = journal_controller.fetch_by_id(journal_id=id)
  topics = topic_controller.fetch_all()
  return render_template(
    'pages/reviewer/manuscript/detail.html', 
    role='Reviewer', 
    topics=topics, 
    manuscript=manuscript,
    back_endpoint=request.form['path'],
    back_text=request.form['breadcrumb']
  )


@reviewer.route('/manuscript/review/list', methods=['GET'])
@login_required
@role_checker.check_permission(role='reviewer')
def manuscript_review_list():
  manuscripts = journal_controller.fetch_by_reviewer()
  statuses = [status for status in journal_controller.status.query.all() if status.name not in ['Submitted', 'Published']]
  return render_template('pages/reviewer/manuscript/review.html', role='Reviewer', statuses=statuses, manuscripts=manuscripts)


@reviewer.route('/manuscript/review', methods=['POST'])
@login_required
@role_checker.check_permission(role='reviewer')
def manuscript_review():
  journal_controller.review(request=request.form)
  return redirect(url_for('reviewer.manuscript_review_list'))


@reviewer.route('/manuscript/reject', methods=['POST'])
@login_required
@role_checker.check_permission(role='reviewer')
def manuscript_reject():
  journal_controller.reject(request=request.form)
  return redirect(url_for('reviewer.manuscript_review_list'))


@reviewer.route('/manuscript/accept', methods=['POST'])
@login_required
@role_checker.check_permission(role='reviewer')
def manuscript_accept():
  journal_controller.accept(request=request.form)
  return redirect(url_for('reviewer.manuscript_review_list'))


@reviewer.route('/manuscript/publish', methods=['POST'])
@login_required
@role_checker.check_permission(role='reviewer')
def manuscript_publish():
  journal_controller.publish(request=request.form)
  return redirect(url_for('base.view_publication'))

app/templates/pages/admin/reviewer/view.html
{% extends "layout/app.html" %}

{% block title %} | Reviewer {% endblock %}

{% block content %}
<div class="ps-sm-3">
  {% include "layout/flash.html" %}
  <h3 class="fw-bold mt-3">Reviewers</h3>
  <button data-bs-toggle="modal" data-bs-target="#addReviewerModal" class="btn btn-success fw-semibold mt-3"><i class="bi bi-plus-square-fill me-2"></i> Add Reviewer</button>
  <div class="col-11 mt-3">
    <table id="reviewerDataTable" class="table table-striped">
      <thead class="table-dark">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Expertise</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody class="table-light fw-semibold">
        {% for reviewer in reviewers %}
          <tr class="align-middle">
            <td scope="col">{{ 'REV{:>04}'.format(reviewer.id) }}</td>
            <td scope="col">{{ reviewer.name }}</td>
            <td scope="col">{{ reviewer.email }}</td>
            <td scope="col">{{ reviewer.reviewer.topic.name }}</td>
            <td scope="col">
              <button class="btn btn-primary btn-sm fw-semibold me-1" data-bs-toggle="modal" data-bs-target="#viewReviewerModal{{ reviewer.id }}"><i class="bi bi-person-square"></i> View</button>
              <button class="btn btn-warning btn-sm fw-semibold me-1" data-bs-toggle="modal" data-bs-target="#updateReviewerModal{{ reviewer.id }}"><i class="bi bi-pencil-square"></i> Edit</button>
              <button class="btn btn-danger btn-sm fw-semibold me-1" data-bs-toggle="modal" data-bs-target="#deleteReviewerModal{{ reviewer.id }}"><i class="bi bi-trash-fill"></i> Delete</button>
            </td>
          </tr>

          <!-- View Reviewer Modal -->
          <div id="viewReviewerModal{{ reviewer.id }}" class="modal fade" role="dialog">
            <div class="modal-dialog modal-lg">
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title fw-bold">View Reviewer</h4>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body d-flex flex-column flex-md-row justify-content-center align-items-center">
                  <div class="col-12 col-md-6 d-flex flex-row justify-content-center align-items-center">
                    {% if reviewer.picture_path %}
                    <img class="rounded-circle shadow-sm" width="240px" height="240px" style="object-fit: cover;" src="{{ url_for('static', filename='images/uploads/' + reviewer.picture_path) }}">
                    {% else %}
                    <img class="rounded-circle shadow-sm" width="240px" height="240px" src="{{ url_for('static', filename='icons/profile.svg') }}">
                    {% endif %}
                  </div>
                  <div class="col-12 col-md-6 d-flex flex-column justify-content-center align-items-center">
                    <div class="w-100">
                      <label class="form-label fw-semibold">Name</label>
                      <p class="fs-6 fw-bold text-dark">{{ reviewer.name }}</p>
                    </div>
                    <div class="w-100">
                      <label class="form-label fw-semibold">Email</label>
                      <a class="text-decoration-none" href="mailto:{{ reviewer.email }}">
                        <p class="fs-6 fw-bold">{{ reviewer.email }}</p>
                      </a>
                    </div>
                    <div class="w-100">
                      <label class="form-label fw-semibold">Telephone</label>
                      <p class="fs-6 fw-bold text-dark">{{ reviewer.telephone }}</p>
                    </div>
                    <div class="w-100">
                      <label class="form-label fw-semibold">Gender</label>
                      {% if reviewer.gender == 'M' %}
                        <p class="fs-6 fw-bold text-primary"><i class="fs-6 bi-gender-male"></i> Male</p>
                      {% else %}
                        <p class="fs-6 fw-bold text-danger"><i class="fs-6 bi-gender-female"></i> Female</p>
                      {% endif %}
                    </div>
                    <div class="w-100">
                      <label class="form-label fw-semibold">Expertise</label>
                      <p class="fs-6 fw-bold text-dark">{{ reviewer.reviewer.topic.name }}</p>
                    </div>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary fw-bold" data-bs-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>

          <!-- Update Reviewer Modal -->
          <div id="updateReviewerModal{{ reviewer.id }}" class="modal fade" role="dialog">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title fw-bold">Update Reviewer</h4>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <form class="d-flex flex-column justify-content-center align-items-center fw-semibold" action="{{ url_for('admin.update_reviewer', id=reviewer.id) }}" method="POST">
                    <div class="mb-2 w-100">
                      <label for="input-email" class="form-label fw-semibold">Name</label>
                      <input type="text" class="form-control" id="input-email" value="{{ reviewer.name }}" name="name" required>
                    </div>
                    <div class="mb-2 w-100">
                      <label for="input-email" class="form-label fw-semibold">Email address</label>
                      <input type="email" class="form-control" id="input-email" value="{{ reviewer.email }}" name="email" required>
                    </div>
                    <div class="mb-2 w-100">
                      <label for="input-email" class="form-label fw-semibold">Telephone</label>
                      <input type="text" class="form-control" id="input-email" value="{{ reviewer.telephone }}" name="telephone" required>
                    </div>
                    <div class="mb-2 w-100">
                      <label for="options" class="form-label fw-semibold">Gender</label>
                      <div id="options" class="w-100 d-flex flex-row justify-content-start">
                        {% set gender = [
                          ('M', 'Male', 'male-radio'),
                          ('F', 'Female', 'female-radio')
                        ] -%}
                  
                        {% for code, label, id in gender %}
                          <div class="form-check me-4">
                            <input class="form-check-input" type="radio" name="gender" id="{{ id }}" value="{{ code }}" {% if reviewer.gender == code %} checked {% endif %}>
                            <label class="form-check-label" for="{{ id }}">
                              {{ label }}
                            </label>
                          </div>
                        {% endfor %}
                      </div>
                    </div>
                    <div class="mb-2 w-100">
                      <label class="form-label fw-bold">Expertise</label>
                      <select class="form-select" id="topic" name="topic" required>
                        {% for topic in topics %}
                        <option value="{{ topic.id }}" {% if topic.id == reviewer.reviewer.topic.id %} selected {% endif %}>{{ topic.name }}</option>
                        {% endfor %}
                      </select>
                    </div>
                    <button type="submit" class="btn btn-dark w-100 fw-bold mt-3 fw-bold border-2 border-dark">Update Profile</button>
                  </form>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary fw-bold" data-bs-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>

          <!-- Delete Reviewer Modal -->
          <div id="deleteReviewerModal{{ reviewer.id }}" class="modal fade" role="dialog">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title fw-bold">Delete Reviewer</h4>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <form action="{{ url_for('admin.delete_reviewer', id=reviewer.id) }}" method="GET">
                    <div>
                      <label class="form-label fw-semibold">Are you sure to delete this reviewer?</label>
                    </div>
                    <div class="mb-2 mt-4 w-100">
                      <button class="btn btn-danger w-100 fw-bold" type="submit">Confirm</button>
                    </div>
                  </form>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary fw-bold" data-bs-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <!-- Add Reviewer Modal -->
  <div id="addReviewerModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title fw-bold">New Reviewer</h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form class="d-flex flex-column justify-content-center align-items-center fw-semibold" action="{{ url_for('admin.create_reviewer') }}" method="POST">
            <div class="mb-2 w-100">
              <label for="input-email" class="form-label">Name</label>
              <input type="text" class="form-control" id="input-email" name="name" required>
            </div>
            <div class="mb-2 w-100">
              <label for="input-email" class="form-label">Email address</label>
              <input type="email" class="form-control" id="input-email" name="email" required>
            </div>
            <div class="mb-2 w-100">
              <label for="input-email" class="form-label">Telephone</label>
              <input type="text" class="form-control" id="input-email" name="telephone" required>
            </div>
            <div class="mb-2 w-100">
              <label for="options" class="form-label">Gender</label>
              <div id="options" class="w-100 d-flex flex-row justify-content-start">
                {% set gender = [
                  ('M', 'Male', 'male-radio'),
                  ('F', 'Female', 'female-radio')
                ] -%}
          
                {% for code, label, id in gender %}
                  <div class="form-check me-4">
                    <input class="form-check-input" type="radio" name="gender" id="{{ id }}" value="{{ code }}">
                    <label class="form-check-label" for="{{ id }}">
                      {{ label }}
                    </label>
                  </div>
                {% endfor %}
              </div>
            </div>
            <div class="mb-2 w-100">
              <label class="form-label fw-bold">Expertise</label>
              <select class="form-select" id="topic" name="topic" required>
                {% for topic in topics %}
                <option value="{{ topic.id }}">{{ topic.name }}</option>
                {% endfor %}
              </select>
            </div>
            <button type="submit" class="btn btn-dark w-100 fw-bold mt-3 fw-bold border-2 border-dark">Create Profile</button>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary fw-bold" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
<script>
$(document).ready(function() {
  $('#reviewerDataTable').DataTable({
    lengthMenu: [[5, 10, 20, -1], [5, 10, 20, "All"]]
  });
});
</script>
{% endblock %}