app/models/topic.py
from app import db

class Topic(db.Model):
  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  name = db.Column(db.String(255), unique=False, nullable=False)
  journal = db.relationship('Journal', back_populates='topic', lazy=True)
  reviewer = db.relationship('Reviewer', back_populates='topic', lazy=True)

  def __repr__(self):
    return '<Topic %r>' % self.name

  def create(self, name):
    topic = Topic(name=name)
    db.session.add(topic)
    db.session.commit()

  def update(self, name, topic_id):
    topic = Topic.query.filter_by(id=topic_id).first()
    topic.name = name
    db.session.commit()

  def delete(self, topic_id):
    topic = Topic.query.filter_by(id=topic_id).first()
    db.session.delete(topic)
    db.session.commit()

app/controllers/topic.py
from flask import redirect, url_for
from app.models.topic import Topic

class TopicController:

  def __init__(self):
    self.topic = Topic()

  def fetch_by_id(self, topic_id):
    return self.topic.query.filter_by(id=topic_id).first()

  def fetch_all(self):
    return self.topic.query.all()

  def create(self, request):
    self.topic.create(name=request['name'])

  def update(self, request, topic_id):
    self.topic.update(name=request['name'], topic_id=topic_id)

  def delete(self, topic_id):
    self.topic.delete(topic_id=topic_id)

app/routes/admin.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required
from app.middlewares.role_checker import RoleChecker
from app.controllers.topic import TopicController
from app.controllers.journal import JournalController
from app.controllers.user import UserController
from app.controllers.applicant import ApplicantController


admin = Blueprint('admin', __name__, template_folder='templates')
role_checker = RoleChecker()

topic_controller = TopicController()
user_controller = UserController()
journal_controller = JournalController()
applicant_controller = ApplicantController()

@admin.route('/', methods=['GET'])
@login_required
@role_checker.check_permission(role='admin')
def index():
  metrics = {
    'topic': len(topic_controller.topic.query.all()),
    'manuscript': len(journal_controller.fetch_by_status(status='Submitted')),
    'published': len(journal_controller.fetch_by_status(status='Published')),
    'applicant': len(applicant_controller.fetch_all())
  }
  return render_template('pages/admin/index.html', metrics=metrics, role='Admin')


@admin.route('/topic', methods=['GET'])
@login_required
@role_checker.check_permission(role='admin')
def view_topic():
  topics = topic_controller.fetch_all()
  return render_template('pages/admin/topic/view.html', topics=topics, role='Admin')


@admin.route('/topic/create', methods=['POST'])
@login_required
@role_checker.check_permission(role='admin')
def create_topic():
  topic_controller.create(request=request.form)
  return redirect(url_for('admin.view_topic'))


@admin.route('/topic/update/<int:id>', methods=['POST'])
@login_required
@role_checker.check_permission(role='admin')
def update_topic(id):
  topic_controller.update(request=request.form, topic_id=id)
  return redirect(url_for('admin.view_topic'))


@admin.route('/topic/delete/<int:id>', methods=['GET'])
@login_required
@role_checker.check_permission(role='admin')
def delete_topic(id):
  topic_controller.delete(topic_id=id)
  return redirect(url_for('admin.view_topic'))

@admin.route('/user', methods=['GET'])
@login_required
@role_checker.check_permission(role='admin')
def view_admin():
  admins = user_controller.fetch_user_by_role(role='admin')
  return render_template('/pages/admin/admin/view.html', admins=admins, role='Admin')


@admin.route('/user/create', methods=['POST'])
@login_required
@role_checker.check_permission(role='admin')
def create_admin():
  user_controller.create(request=request.form, role='admin')
  return redirect(url_for('admin.view_admin'))


@admin.route('/user/update/<int:id>', methods=['POST'])
@login_required
@role_checker.check_permission(role='admin')
def update_admin(id):
  user_controller.update(request=request.form, user_id=id)
  return redirect(url_for('admin.view_admin'))


@admin.route('/user/delete/<int:id>', methods=['GET'])
@login_required
@role_checker.check_permission(role='admin')
def delete_admin(id):
  user_controller.delete(user_id=id)
  return redirect(url_for('admin.view_admin'))


@admin.route('/reviewer', methods=['GET'])
@login_required
@role_checker.check_permission(role='admin')
def view_reviewer():
  reviewers = user_controller.fetch_user_by_role(role='reviewer')
  topics = topic_controller.fetch_all()
  return render_template('/pages/admin/reviewer/view.html', reviewers=reviewers, role='Admin', topics=topics)


@admin.route('/reviewer/create', methods=['POST'])
@login_required
@role_checker.check_permission(role='admin')
def create_reviewer():
  user_controller.create(request=request.form, role='reviewer')
  return redirect(url_for('admin.view_reviewer'))


@admin.route('/reviewer/update/<int:id>', methods=['POST'])
@login_required
@role_checker.check_permission(role='admin')
def update_reviewer(id):
  user_controller.update(request=request.form, user_id=id)
  return redirect(url_for('admin.view_reviewer'))


@admin.route('/reviewer/delete/<int:id>', methods=['GET'])
@login_required
@role_checker.check_permission(role='admin')
def delete_reviewer(id):
  user_controller.delete(user_id=id)
  return redirect(url_for('admin.view_reviewer'))


@admin.route('/applicant/', methods=['GET'])
@login_required
@role_checker.check_permission(role='admin')
def view_applicant():
  applicants = applicant_controller.fetch_all()
  return render_template('pages/admin/applicant/view.html', role='Admin', applicants=applicants)


@admin.route('/applicant/download/<filename>', methods=['GET'])
@login_required
@role_checker.check_permission(role='admin')
def cv_download(filename):
  return applicant_controller.cv_download(filename)


@admin.route('/applicant/receive', methods=['POST'])
@login_required
@role_checker.check_permission(role='admin')
def receive_applicant():
  applicant_controller.receive(request=request.form)
  return redirect(url_for('admin.view_applicant'))


@admin.route('/applicant/reject', methods=['POST'])
@login_required
@role_checker.check_permission(role='admin')
def reject_applicant():
  applicant_controller.reject(request=request.form)
  return redirect(url_for('admin.view_applicant'))

app/templates/pages/admin/topic/view.html
{% extends "layout/app.html" %}

{% block title %} | Topic {% endblock %}

{% block content %}
<div class="ps-sm-3">
  {% include "layout/flash.html" %}
  <h3 class="fw-bold mt-3">Topic</h3>
  <button class="btn btn-success fw-semibold mt-3" data-bs-toggle="modal" data-bs-target="#addTopicModal"><i class="bi bi-plus-square-fill me-2"></i> Add Topic</button>
  <div class="col-11 mt-3">
    <table id="topicDataTable" class="table table-striped">
      <thead class="table-dark">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody class="table-light fw-semibold">
        {% for topic in topics %}
          <tr class="align-middle">
            <td scope="col">{{ 'T{:>04}'.format(topic.id) }}</td>
            <td scope="col">{{ topic.name }}</td>
            <td scope="col">
              <button class="btn btn-warning btn-sm fw-semibold me-1" data-bs-toggle="modal" data-bs-target="#editTopicModal{{ topic.id }}"><i class="bi bi-pencil-square"></i> Edit</button>
              <button class="btn btn-danger btn-sm fw-semibold me-1" data-bs-toggle="modal" data-bs-target="#deleteTopicModal{{ topic.id }}"><i class="bi bi-trash-fill"></i> Delete</button>
            </td>
          </tr>
          <!-- Edit Topic Modal -->
          <div id="editTopicModal{{ topic.id }}" class="modal fade" role="dialog">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title fw-bold">Edit Topic</h4>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <form action="{{ url_for('admin.update_topic', id=topic.id) }}" method="POST" enctype="multipart/form-data">
                    <div class="mb-2">
                      <label class="form-label fw-semibold">Topic Name</label>
                      <input type="text" class="form-control" name="name" required value="{{ topic.name }}">
                    </div>
                    <div class="mb-2 mt-4 w-100">
                      <button class="btn btn-success w-100 fw-bold" type="submit">Confirm</button>
                    </div>
                  </form>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary fw-bold" data-bs-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>

          <!-- Delete Topic Modal -->
          <div id="deleteTopicModal{{ topic.id }}" class="modal fade" role="dialog">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title fw-bold">Delete Topic</h4>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <form action="{{ url_for('admin.delete_topic', id=topic.id) }}" method="GET" enctype="multipart/form-data">
                    <div>
                      <label class="form-label fw-semibold">Are you sure to delete this topic?</label>
                    </div>
                    <div class="mb-2 mt-4 w-100">
                      <button class="btn btn-danger w-100 fw-bold" type="submit">Confirm</button>
                    </div>
                  </form>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary fw-bold" data-bs-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <!-- Add Topic Modal -->
  <div id="addTopicModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title fw-bold">New Topic</h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="{{ url_for('admin.create_topic') }}" method="POST" enctype="multipart/form-data">
            <div class="mb-2">
              <label class="form-label fw-semibold">Topic Name</label>
              <input type="text" class="form-control" name="name" required>
            </div>
            <div class="mb-2 mt-4 w-100">
              <button class="btn btn-success w-100 fw-bold" type="submit">Confirm</button>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary fw-bold" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
<script>
$(document).ready(function() {
  $('#topicDataTable').DataTable({
    lengthMenu: [[5, 10, 20, -1], [5, 10, 20, "All"]]
  });
});
</script>
{% endblock %}