app/models/journal.py
from app import db
from datetime import datetime


class Journal(db.Model):
  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  title = db.Column(db.String(255), unique=False, nullable=False)
  abstract = db.Column(db.Text, unique=False, nullable=False)
  journal_path = db.Column(db.String(255), unique=False, nullable=False)
  upload_time = db.Column(db.DateTime, nullable=False)
  user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), unique=False, nullable=False)
  topic_id = db.Column(db.Integer, db.ForeignKey('topic.id', ondelete='SET NULL'), unique=False, nullable=True)
  topic = db.relationship('Topic', uselist=False, back_populates='journal', lazy=True)
  author = db.relationship('Author', backref='journal', lazy=True, cascade='delete,delete-orphan')
  journal_log = db.relationship('JournalLog', uselist=False, backref='journal', lazy=True, cascade='delete,delete-orphan')

  def __repr__(self):
    return '<Journal %r>' % self.title

  def create(self, title, abstract, journal_path, user_id, topic_id):
    journal = Journal(
      title=title,
      abstract=abstract,
      journal_path=journal_path,
      upload_time=datetime.now(),
      user_id=user_id,
      topic_id=topic_id
    )

    db.session.add(journal)
    db.session.commit()
    db.session.flush()

    return journal

  def update(self, journal_id, title, abstract, journal_path, user_id, topic_id):
    journal = Journal.query.filter_by(id=journal_id).first()
    journal.title = title
    journal.abstract = abstract
    journal.user_id = user_id
    journal.topic_id = topic_id
    journal.upload_time = datetime.now()

    if journal_path is not None:
      journal.journal_path = journal_path

    db.session.commit()

  def delete(self, journal_id):
    journal = Journal.query.filter_by(id=journal_id).first()
    db.session.delete(journal)
    db.session.commit()

app/models/user.py
from app import db
from flask_login import UserMixin
from datetime import datetime


class User(UserMixin, db.Model):
  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  name = db.Column(db.String(255), unique=False, nullable=False)
  email = db.Column(db.String(255), unique=True, nullable=False)
  telephone = db.Column(db.String(255), unique=True, nullable=False)
  password = db.Column(db.String(255), unique=False, nullable=False)
  gender = db.Column(db.String(2), unique=False, nullable=False)
  is_verified = db.Column(db.Integer, unique=False, nullable=False)
  registered_date = db.Column(db.DateTime, nullable=False)
  role_id = db.Column(db.Integer, db.ForeignKey('role.id', ondelete='CASCADE'), unique=False, nullable=False)
  picture_path = db.Column(db.String(255), nullable=True)
  verification = db.relationship('Verification', backref='user', lazy=True)
  journal = db.relationship('Journal', backref='user', lazy=True, cascade='delete,delete-orphan')
  reviewer = db.relationship('Reviewer', uselist=False, backref='user', lazy=True, cascade='delete,delete-orphan')
  role = db.relationship('Role', back_populates='user', lazy=True)

  def __repr__(self):
    return '<User %r>' % self.name

  def create(self, name, email, telephone, password, gender, role_id, is_verified=None):
    user = User(
      name=name,
      email=email,
      telephone=telephone,
      password=password,
      gender=gender,
      is_verified= 0 if is_verified is None else is_verified,
      registered_date=datetime.now(),
      role_id=role_id
    )
    db.session.add(user)
    db.session.commit()

  def update(self, name, email, telephone, gender, id):
    user = User.query.filter_by(id=id).first()
    user.name = name
    user.email = email
    user.telephone = telephone
    user.gender = gender
    db.session.commit()

  def update_password(self, password, id):
    user = User.query.filter_by(id=id).first()
    user.password = password
    db.session.commit()

  def update_image(self, filename, id):
    user = User.query.filter_by(id=id).first()
    user.picture_path = filename
    db.session.commit()

  def verified_user(self, id):
    user = User.query.filter_by(id=id).first()
    user.is_verified = 1
    db.session.commit()

  def delete(self, id):
    user = User.query.filter_by(id=id).first() 
    db.session.delete(user)
    db.session.commit()

app/controllers/journal.py
from flask import redirect, url_for, flash, send_file
from flask_login import current_user
import os
from app.models.journal import Journal
from app.models.journal_log import JournalLog
from app.models.author import Author
from app.models.status import Status
from app.models.reviewer import Reviewer
from app.utils.mailer import send_review_notification, send_custom_mail, send_acceptance_notification, send_publication_notification
from app.utils.file import save_doc, delete_doc
from app.config import Config


class JournalController:
  
  def __init__(self):
    self.journal = Journal()
    self.author = Author()
    self.status = Status()
    self.journal_log = JournalLog()
    self.reviewer = Reviewer()

  def fetch_by_id(self, journal_id):
    return self.journal.query.filter_by(id=journal_id).first()

  def fetch_all(self, sort_by_time=False):
    return self.journal.query.filter_by(user_id=current_user.id).all()

  def fetch_publication(self, year=None):
    status_id = self.status.query.filter_by(name='Published').first().id
    journals = self.journal.query.join(JournalLog).filter(
      JournalLog.status_id == status_id
    ).order_by(JournalLog.timestamp.desc()).all()
    publication_year = [journal.journal_log.timestamp.year for journal in journals]
    if year is not None:
      return [journal for journal in journals if journal.journal_log.timestamp.year == year]
    return (journals, publication_year)

  def fetch_by_reviewer(self):
    reviewer = self.reviewer.query.filter_by(user_id=current_user.id).first()
    journals = self.journal.query.join(JournalLog).filter(JournalLog.reviewer_id == reviewer.id).all()
    return [journal for journal in journals if journal.journal_log.status.name not in ['Submitted', 'Published']]

  def fetch_by_status(self, status):
    status_id = self.status.query.filter_by(name=status).first().id
    return self.journal.query.join(JournalLog).filter_by(status_id=status_id).all()

  def fetch_statuses(self):
    return self.status.query.all()

  def create(self, request, doc):
    doc_path = save_doc(doc)

    if doc_path is False:
      flash('Wrong file type. Allowed file type is .pdf', 'warning')
      return redirect(url_for('home.journal_create'))

    journal = self.journal.create(
      title=request['title'],
      abstract=request['abstract'],
      journal_path=doc_path,
      user_id=current_user.id,
      topic_id=request['topic'],
    )

    self.journal_log.create(
      journal_id=journal.id,
      status_id=self.status.query.filter_by(name='Submitted').first().id
    )

    authors_name = request.getlist('names[]')
    authors_email = request.getlist('emails[]')
    authors_institution = request.getlist('institutions[]')
    n_author = len(authors_name)

    for index in range(0, n_author):
      self.author.create(
        name=authors_name[index],
        email=authors_email[index],
        institution=authors_institution[index],
        journal_id=journal.id
      )

    return redirect(url_for('home.journal_view_detail', id=journal.id))
  
  def update(self, request, doc):
    doc_path = save_doc(doc) if doc else None

    if doc_path is False:
      flash('Wrong file type. Allowed file type is .pdf, .doc, and .docx', 'warning')
      return redirect(url_for('home.journal_create'))
    
    journal = self.fetch_by_id(journal_id=request['id'])

    delete_doc(journal.journal_path) if doc_path is not None else None
      
    self.journal.update(
      journal_id=request['id'],
      title=request['title'],
      abstract=request['abstract'],
      journal_path=doc_path,
      user_id=current_user.id,
      topic_id=request['topic'],
    )
    
    journal_log = self.journal_log.query.filter_by(journal_id=request['id']).first()

    if journal_log.status.name == 'Rejected':
      self.journal_log.update(
        journal_id=journal.id,
        status_id=self.status.query.filter_by(name='Submitted').first().id
      )

    old_author_ids = [author.id for author in journal.author]

    updated_author_ids = [int(id) for id in request.getlist('ids[]')]
    authors_name = request.getlist('names[]')
    authors_email = request.getlist('emails[]')
    authors_institution = request.getlist('institutions[]')

    n_old_author = len(updated_author_ids)
    n_submitted_author = len(authors_name)

    ids_to_update = list(set(updated_author_ids) & set(old_author_ids))
    ids_to_delete = list(set(old_author_ids) - set(updated_author_ids))

    for index in range(0, n_old_author):
      if updated_author_ids[index] in ids_to_update:
        self.author.update(
          author_id=updated_author_ids[index],
          name=authors_name[index],
          email=authors_email[index],
          institution=authors_institution[index],
          journal_id=journal.id
        )

    for index in range(n_old_author, n_submitted_author):
      self.author.create(
        name=authors_name[index],
        email=authors_email[index],
        institution=authors_institution[index],
        journal_id=journal.id
      )

    for id_to_delete in ids_to_delete:
      self.author.delete(author_id=id_to_delete)

    return redirect(url_for('home.journal_view_detail', id=journal.id))

  def delete(self, request):
    journal = self.fetch_by_id(journal_id=request['id'])
    delete_doc(journal.journal_path)
    self.journal.delete(journal_id=request['id'])

  def download(self, filename):
    directory = os.path.join('static/docs/uploads', filename)
    return send_file(directory, as_attachment=True)

  def review(self, request):
    journal = self.fetch_by_id(journal_id=request['id'])

    reviewer = self.reviewer.query.filter_by(user_id=current_user.id).first()
    self.journal_log.update(
      journal_id=request['id'],
      status_id=self.status.query.filter_by(name='In Review').first().id,
      reviewer_id=reviewer.id
    )
    
    send_review_notification(
      to=journal.user.email,
      title=journal.title
    )

  def reject(self, request):
    journal = self.fetch_by_id(journal_id=request['id'])
    
    self.journal_log.update(
      journal_id=request['id'],
      status_id=self.status.query.filter_by(name='Rejected').first().id,
    )

    send_custom_mail(
      to=journal.user.email,
      subject=request['subject'],
      content=request['messages']
    )

  def accept(self, request):
    journal = self.fetch_by_id(journal_id=request['id'])

    self.journal_log.update(
      journal_id=request['id'],
      status_id=self.status.query.filter_by(name='Accepted').first().id
    )

    send_acceptance_notification(
      to=journal.user.email,
      title=journal.title
    )
  
  def publish(self, request):
    journal = self.fetch_by_id(journal_id=request['id'])

    self.journal_log.update(
      journal_id=request['id'],
      status_id=self.status.query.filter_by(name='Published').first().id
    )

    send_publication_notification(
      to=journal.user.email,
      title=journal.title,
      series=journal.journal_log.timestamp.year
    )

app/controllers/user.py
from flask import redirect, url_for, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import current_user
import random
import string
from app.models.user import User
from app.models.role import Role
from app.models.reviewer import Reviewer
from app.utils.file import save_image, delete_image
from app.utils.mailer import send_account_credential


class UserController:
  
  def __init__(self):
    self.user = User()
    self.role = Role()
    self.reviewer = Reviewer()

  def fetch_user_by_role(self, role):
    role_id = self.role.query.filter_by(name=role).first().id
    return self.user.query.filter(User.id != current_user.id, User.role_id == role_id).all()

  def get_profile(self, user_id):
    return self.user.query.filter_by(id=user_id).first()

  def create(self, request, role):
    user = self.user.query.filter_by(email=request['email']).first()
    if user:
      return flash('Email has already existed', 'warning')

    user = self.user.query.filter_by(telephone=request['telephone']).first()
    if user:
      return flash('Telephone has already existed', 'warning')

    password = ''.join(random.choice(string.ascii_letters) for i in range(20))
    hashed_password = generate_password_hash(password, method='sha256')

    self.user.create(
      name=request['name'],
      email=request['email'],
      telephone=request['telephone'],
      password=hashed_password,
      gender=request['gender'],
      role_id=self.role.query.filter_by(name=role).first().id
    )

    if role == 'reviewer':
      user = self.user.query.filter_by(email=request['email']).first()
      
      self.reviewer.create(
        user_id=user.id,
        topic_id=request['topic']
      )

    send_account_credential(to=request['email'], password=password)
    return flash('User has been created, credentials has been sent to user.', 'info')

  def update(self, request, user_id):
    self.user.update(
      name=request['name'],
      email=request['email'],
      telephone=request['telephone'],
      gender=request['gender'],
      id=user_id
    )

    user = self.user.query.filter_by(email=request['email']).first()
    if user.role.name == 'reviewer':
      
      self.reviewer.update(
        user_id=user.id,
        topic_id=request['topic']
      )

  def update_profile_image(self, photo, user_id):
    user = self.get_profile(user_id=user_id)

    filename = save_image(photo)
    
    if filename is False:
      flash('Wrong file type. Allowed file type is .jpg .png .jpeg', 'warning')
      return redirect(url_for('base.profile'))

    delete_image(user.picture_path) if user.picture_path is not None else None

    self.user.update_image(
      filename=filename,
      id=user_id
    )

    return redirect(url_for('base.profile'))

  def delete(self, user_id):
    self.user.delete(id=user_id)

app/routes/home.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required
from app.middlewares.role_checker import RoleChecker
from app.controllers.topic import TopicController
from app.controllers.journal import JournalController


home = Blueprint('home', __name__, template_folder='templates')

role_checker = RoleChecker()
topic_controller = TopicController()
journal_controller = JournalController()

@home.route('/', methods=['GET'])
@login_required
@role_checker.check_permission(role='user')
def index():
  return redirect(url_for('base.view_publication'))


@home.route('/journal/', methods=['GET'])
@login_required
@role_checker.check_permission(role='user')
def journal_view():
  journals = journal_controller.fetch_all()
  topics = topic_controller.fetch_all()
  statuses = journal_controller.fetch_statuses()
  return render_template('pages/user/journal/view.html', role='User', topics=topics, journals=journals, statuses=statuses)


@home.route('/journal/detail/<id>', methods=['GET'])
@login_required
@role_checker.check_permission(role='user')
def journal_view_detail(id):
  journal = journal_controller.fetch_by_id(journal_id=id)
  topics = topic_controller.fetch_all()
  return render_template('pages/user/journal/detail.html', role='User', topics=topics, journal=journal)


@home.route('/journal/create', methods=['GET', 'POST'])
@login_required
@role_checker.check_permission(role='user')
def journal_create():
  if request.method == 'POST':
    return journal_controller.create(request=request.form, doc=request.files['doc'])
  
  topics = topic_controller.fetch_all()
  return render_template('pages/user/journal/add.html', role='User', topics=topics)


@home.route('/journal/update/<id>', methods=['GET', 'POST'])
@login_required
@role_checker.check_permission(role='user')
def journal_update(id):
  if request.method == 'POST':
    return journal_controller.update(request=request.form, doc=request.files['doc'])
  
  topics = topic_controller.fetch_all()
  journal = journal_controller.fetch_by_id(journal_id=id)
  return render_template('pages/user/journal/edit.html', role='User', topics=topics, journal=journal)


@home.route('/journal/delete', methods=['POST'])
@login_required
@role_checker.check_permission(role='user')
def journal_delete():
  journal_controller.delete(request=request.form)
  return redirect(url_for('home.journal_view'))


@home.route('/journal/download/<filename>', methods=['GET'])
@login_required
@role_checker.check_permission(role='user')
def journal_download(filename):
  return journal_controller.download(filename)
  

app/templates/pages/user/journal/detail.html
{% extends "layout/app.html" %}

{% block title %} | {{ journal.title }} {% endblock %}

{% block content %}
<div class="ps-sm-3 pb-5">
  <nav class="col-12 col-md-11 d-flex mt-4 flex-column flex-md-row justify-content-between align-items-start align-items-md-center" aria-label="breadcrumb">
    <ol class="breadcrumb fw-semibold col-12 col-md-6 d-flex flex-row">
      <li class="breadcrumb-item fw-semibold text-decoration-none"><a href="{{ url_for('home.journal_view') }}">My Journal</a></li>
      <li class="breadcrumb-item fw-semibold active" aria-current="page">{{ journal.title }}</li>
    </ol>
    <div class="col-12 col-md-6 d-flex flex-row">
      {% if journal.journal_log.status.name in ['Submitted', 'Rejected']  %}
      <a href="{{ url_for('home.journal_update', id=journal.id) }}" type="button" class="btn btn-warning btn-sm fw-semibold me-2 ms-auto"><i class="bi bi-pencil-square"></i> Edit</a>
      <button class="btn btn-danger btn-sm fw-semibold" data-bs-toggle="modal" data-bs-target="#deleteJournal"><i class="bi bi-trash-fill"></i> Delete</button>
      {% endif %}
    </div>
  </nav>
  <h3 class="fw-bold mt-4">{{ journal.title }}</h3>
  <h5 class="fw-semibold me-2 mb-0">Status: <span class="{{ journal.journal_log.status.color }}">{{ journal.journal_log.status.name }}</span></span></p>
  <div class="d-flex flex-column mt-3 col-12 col-md-11">
    <h5 class="fw-semibold">Abstract: </h5>
    <h6 class="me-2 mb-0" style="text-align: justify;">
      {{ journal.abstract }}
    </h6>
  </div>
  <div class="d-flex flex-column mt-3 col-12">
    <h5 class="fw-semibold">Author: </h5>
    {% for author in journal.author %}
    <h6 class="fw-semibold me-2 mb-1">
      [{{ loop.index0 + 1 }}] {{ author.name }}
    </h6>
    <div class="col-12 d-flex flex-column flex-md-row">
      <h6 class="fw-semibold mb-2 col-md-4 col-12">
        &emsp;&nbsp;Institution: {{ author.institution }}
      </h6>
      <h6 class="fw-semibold mb-2 col-md-4 col-12">
        Email: <span><a href="mailto:{{ author.email }}" class="mb-0 text-decoration-none">{{ author.email }}</a></span>
      </h6>
    </div>
    {% endfor %}
  </div>
  <!-- Delete Journal Modal -->
  <div id="deleteJournal" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title fw-bold">Delete Journal</h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="{{ url_for('home.journal_delete') }}" method="POST">
            <input type="hidden" class="form-control" id="input-id" name="id" value="{{ journal.id }}" required>
            <div>
              <label class="form-label fw-semibold">Are you sure to delete this journal?</label>
            </div>
            <div class="mb-2 mt-4 w-100">
              <button class="btn btn-danger w-100 fw-bold" type="submit">Confirm</button>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary fw-bold" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <div class="col-12 col-md-11 d-flex flex-column align-items-center justify-content-center mt-3">
    <h5 class="fw-semibold align-self-start">PDF: </h5>
    <iframe class="col-12 py-2 px-md-0 vh-100" src="{{ url_for('static', filename='docs/uploads/' + journal.journal_path) }}#toolbar=0">
  </div>

</div>
{% endblock %}

app/templates/pages/user/journal/view.html
{% extends "layout/app.html" %}

{% block title %} | Journal {% endblock %}

{% block content %}
<div class="ps-sm-3 pb-5">
  <h3 class="fw-bold my-3">My Journals</h3>
  <div class="col-12 col-md-11 mb-4 d-flex flex-column flex-md-row align-items-center justify-content-between">
    <div class="col-12 col-md-7">
      <input id="searchJournal" class="form-control" type="text" placeholder="Search Your Journal...">
    </div>
    <div class="col-12 col-md-4">
      <select id="filterJournalByStatus" class="form-select">
        <option selected>All</option>
        {% for status in statuses %}
        <option value="{{ status.id }}">{{ status.name }}</option>
        {% endfor %}
      </select>
    </div>
  </div>
  {% if journals|length == 0 %}
  <div class="col-12 col-md-11 d-flex flex-column align-items-center justify-content-center">
    <img class="col-9 col-md-4 mt-5" src="{{ url_for('static', filename='images/nothing.svg') }}">
    <h4 class="fw-semibold mt-4">No Journal Submitted</h4>
  </div>
  {% endif %}
  <div id="myJournals" class="col-12 col-md-11">
    {% for journal in journals %}
    <div style="border-radius: 16px;" class="journal border border-1 px-3 py-2 my-3">
      <p id="title" class="fs-4 fw-bold mb-1">{{ journal.title }}</p>
      <div class="d-flex align-items-center flex-row flex-wrap">
        <p style="font-size: medium;" class="fw-semibold me-2 mb-0">Author: </p>
        {% for author in journal.author %}
        <p style="font-size: medium;" class="fw-semibold me-2 mb-0">
          [{{ loop.index0 + 1 }}]
          <span><a href="mailto:{{ author.email }}" class="mb-0 text-decoration-none">{{ author.name }}</a></span>
        </p>
        {% endfor %}
      </div>
      <p id="status" style="font-size: medium;" class="fw-semibold me-2 mb-0">Status: <span class="{{ journal.journal_log.status.color }}">{{ journal.journal_log.status.name }}</span></p>
      <p style="font-size: medium;" class="fw-semibold me-2 mb-0">Last updated: <span class="text-secondary">{{ journal.journal_log.timestamp }}</span></p>
      <div class="d-flex align-items-center mt-2">
        <a href="{{ url_for('home.journal_download', filename=journal.journal_path) }}" target="_blank" type="button" class="btn btn-sm fw-semibold me-2 ms-auto text-primary"><i class="bi bi-download"></i> Download File</a>
        <a href="{{ url_for('home.journal_view_detail', id=journal.id) }}" type="button" class="btn btn-primary btn-sm fw-semibold me-2"><i class="bi bi-file-earmark"></i> View Detail</a>
        {% if journal.journal_log.status.name in ['Submitted', 'Rejected']  %}
        <a href="{{ url_for('home.journal_update', id=journal.id) }}" type="button" class="btn btn-warning btn-sm fw-semibold me-2"><i class="bi bi-pencil-square"></i> Edit</a>
        <button class="btn btn-danger btn-sm fw-semibold" data-bs-toggle="modal" data-bs-target="#deleteJournal{{ journal.id }}"><i class="bi bi-trash-fill"></i> Delete</button>
        {% endif %}
      </div>
    </div>

    <!-- Delete Journal Modal -->
    <div id="deleteJournal{{ journal.id }}" class="modal fade" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title fw-bold">Delete Journal</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form action="{{ url_for('home.journal_delete') }}" method="POST">
              <input type="hidden" class="form-control" name="id" value="{{ journal.id }}" required>
              <div>
                <label class="form-label fw-semibold">Are you sure to delete this journal with title "{{ journal.title }}"?</label>
              </div>
              <div class="mb-2 mt-4 w-100">
                <button class="btn btn-danger w-100 fw-bold" type="submit">Confirm</button>
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary fw-bold" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

{% block js %}
<script>
  $(document).ready(function() {
    $("#searchJournal").on("keyup", function() {
      var search = $(this).val().toLowerCase();
      $("#myJournals div.journal").filter(function() {
        $(this).toggle($(this).find("#title").text().toLowerCase().indexOf(search) > -1);
        return;
      });
    });

    $("#filterJournalByStatus").on("change", function() {
      var filter = $(this).children("option:selected").text().toLowerCase();
      $("#myJournals div.journal").filter(function() {
        if(filter === 'all') {
          $(this).toggle(true);
        } else {
          $(this).toggle($(this).find("#status span").text().toLowerCase() === filter);
        }
      });
    });
  });
</script>
{% endblock  %}