app/models/reviewer.py
from app import db


class Reviewer(db.Model):
  id = db.Column(db.Integer, primary_key=True, autoincrement=True)
  user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), unique=True, nullable=False)
  topic_id = db.Column(db.Integer, db.ForeignKey('topic.id', ondelete='SET NULL'), unique=False, nullable=True)
  journal_log = db.relationship('JournalLog', backref='reviewer', lazy=True)
  topic = db.relationship('Topic', back_populates='reviewer', lazy=True)

  def __repr__(self):
    return '<Reviewer %r>' % self.user_id
  
  def create(self, user_id, topic_id):
    reviewer = Reviewer(
      user_id=user_id,
      topic_id=topic_id
    )

    db.session.add(reviewer)
    db.session.commit()

  def update(self, user_id, topic_id):
    reviewer = Reviewer.query.filter_by(user_id=user_id).first()
    reviewer.topic_id = topic_id

    db.session.commit()
  

app/routes/reviewer.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from app.controllers.auth import AuthController
from app.controllers.journal import JournalController
from app.controllers.topic import TopicController
from app.middlewares.role_checker import RoleChecker


reviewer = Blueprint('reviewer', __name__, template_folder='templates')
role_checker = RoleChecker()
journal_controller = JournalController()
topic_controller = TopicController()

@reviewer.route('/', methods=['GET'])
@login_required
@role_checker.check_permission(role='reviewer')
def index():
  return redirect(url_for('base.view_publication'))


@reviewer.route('/manuscript/submission', methods=['GET'])
@login_required
@role_checker.check_permission(role='reviewer')
def manuscript_submission():
  manuscripts = journal_controller.fetch_by_status(status='Submitted')
  topics = topic_controller.fetch_all()
  return render_template('pages/reviewer/manuscript/submission.html', role='Reviewer', manuscripts=manuscripts, topics=topics)


@reviewer.route('/manuscript/download/<filename>', methods=['GET'])
@login_required
@role_checker.check_permission(role='reviewer')
def manuscript_download(filename):
  return journal_controller.download(filename)


@reviewer.route('/manuscript/detail/<id>', methods=['GET', 'POST'])
@login_required
@role_checker.check_permission(role='reviewer')
def manuscript_view_detail(id):
  manuscript = journal_controller.fetch_by_id(journal_id=id)
  topics = topic_controller.fetch_all()
  return render_template(
    'pages/reviewer/manuscript/detail.html', 
    role='Reviewer', 
    topics=topics, 
    manuscript=manuscript,
    back_endpoint=request.form['path'],
    back_text=request.form['breadcrumb']
  )


@reviewer.route('/manuscript/review/list', methods=['GET'])
@login_required
@role_checker.check_permission(role='reviewer')
def manuscript_review_list():
  manuscripts = journal_controller.fetch_by_reviewer()
  statuses = [status for status in journal_controller.status.query.all() if status.name not in ['Submitted', 'Published']]
  return render_template('pages/reviewer/manuscript/review.html', role='Reviewer', statuses=statuses, manuscripts=manuscripts)


@reviewer.route('/manuscript/review', methods=['POST'])
@login_required
@role_checker.check_permission(role='reviewer')
def manuscript_review():
  journal_controller.review(request=request.form)
  return redirect(url_for('reviewer.manuscript_review_list'))


@reviewer.route('/manuscript/reject', methods=['POST'])
@login_required
@role_checker.check_permission(role='reviewer')
def manuscript_reject():
  journal_controller.reject(request=request.form)
  return redirect(url_for('reviewer.manuscript_review_list'))


@reviewer.route('/manuscript/accept', methods=['POST'])
@login_required
@role_checker.check_permission(role='reviewer')
def manuscript_accept():
  journal_controller.accept(request=request.form)
  return redirect(url_for('reviewer.manuscript_review_list'))


@reviewer.route('/manuscript/publish', methods=['POST'])
@login_required
@role_checker.check_permission(role='reviewer')
def manuscript_publish():
  journal_controller.publish(request=request.form)
  return redirect(url_for('base.view_publication'))

app/templates/pages/reviewer/manuscript/detail.html
{% extends "layout/app.html" %}

{% block title %} | {{ manuscript.title }} {% endblock %}

{% block content %}
<div class="ps-sm-3 pb-5">
  <nav class="col-12 col-md-11 d-flex mt-4 flex-column flex-md-row justify-content-between align-items-start align-items-md-center" aria-label="breadcrumb">
    <ol class="breadcrumb fw-semibold col-12 col-md-6 d-flex flex-row">
      <li class="breadcrumb-item fw-semibold text-decoration-none"><a href="{{ url_for(back_endpoint) }}">{{ back_text }}</a></li>
      <li class="breadcrumb-item fw-semibold active" aria-current="page">{{ manuscript.title }}</li>
    </ol>

    <div class="col-12 col-md-6 d-flex flex-row">
      {% if back_endpoint == 'reviewer.manuscript_submission' %}
      <button class="btn btn-success btn-sm fw-semibold ms-auto" data-bs-toggle="modal" data-bs-target="#reviewManuscript"><i class="bi bi-search"></i> Review</button>
      {% endif %}
      {% if back_endpoint != 'reviewer.manuscript_submission' and manuscript.journal_log.status.name == 'In Review' %}
      <button class="btn btn-success btn-sm fw-semibold ms-auto me-2" data-bs-toggle="modal" data-bs-target="#publishManuscript"><i class="bi bi-journal-check"></i> Published</button>
      <button class="btn btn-primary btn-sm fw-semibold me-2" data-bs-toggle="modal" data-bs-target="#acceptManuscript"><i class="bi bi-check-lg"></i> Accepted</button>
      <button class="btn btn-danger btn-sm fw-semibold" data-bs-toggle="modal" data-bs-target="#rejectManuscript"><i class="bi bi-x-lg"></i> Reject</button>
      {% endif %}
      {% if manuscript.journal_log.status.name == 'Accepted' %}
      <button class="btn btn-success btn-sm fw-semibold ms-auto me-2" data-bs-toggle="modal" data-bs-target="#publishManuscript"><i class="bi bi-journal-check"></i> Published</button>
      {% endif %}
    </div>
  </nav>
  <h3 class="fw-bold mt-4">{{ manuscript.title }}</h3>
  <h5 class="fw-semibold me-2 mb-0">Status: <span class="{{ manuscript.journal_log.status.color }}">{{ manuscript.journal_log.status.name }}</span></span></p>
  <div class="d-flex flex-column mt-3 col-12 col-md-11">
    <h5 class="fw-semibold">Abstract: </h5>
    <h6 class="me-2 mb-0" style="text-align: justify;">
      {{ manuscript.abstract }}
    </h6>
  </div>
  <div class="d-flex flex-column mt-3 col-12">
    <h5 class="fw-semibold">Author: </h5>
    {% for author in manuscript.author %}
    <h6 class="fw-semibold me-2 mb-1">
      [{{ loop.index0 + 1 }}] {{ author.name }}
    </h6>
    <div class="col-12 d-flex flex-column flex-md-row">
      <h6 class="fw-semibold mb-2 col-md-4 col-12">
        &emsp;&nbsp;Institution: {{ author.institution }}
      </h6>
      <h6 class="fw-semibold mb-2 col-md-4 col-12">
        Email: <span><a href="mailto:{{ author.email }}" class="mb-0 text-decoration-none">{{ author.email }}</a></span>
      </h6>
    </div>
    {% endfor %}
  </div>

  <!-- Accept Manuscript Modal -->
  <div id="publishManuscript" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title fw-bold">Publish Manuscript</h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="{{ url_for('reviewer.manuscript_publish') }}" class="d-flex flex-column justify-content-center align-items-center fw-semibold" method="POST">
            <input type="hidden" name="id" value="{{ manuscript.id }}" required>
            <div class="w-100">
              <p class="fs-6 form-label fw-semibold">Are you sure to publish the manuscript with title: <br/><span class="fw-semibold fs-5">{{ manuscript.title }}</span></p>
            </div>
            <button type="submit" class="btn btn-primary w-100 fw-bold mt-3 fw-bold">Publish Manuscript</button>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary fw-bold" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

  <!-- Accept Manuscript Modal -->
  <div id="acceptManuscript" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title fw-bold">Accept Manuscript</h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="{{ url_for('reviewer.manuscript_accept') }}" class="d-flex flex-column justify-content-center align-items-center fw-semibold" method="POST">
            <input type="hidden" name="id" value="{{ manuscript.id }}" required>
            <div class="w-100">
              <p class="fs-6 form-label fw-semibold">Are you sure to accept the manuscript with title: <br/><span class="fw-semibold fs-5">{{ manuscript.title }}</span></p>
            </div>
            <button type="submit" class="btn btn-primary w-100 fw-bold mt-3 fw-bold">Accept Manuscript</button>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary fw-bold" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

   <!-- Review Manuscript Modal -->
   <div id="reviewManuscript" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title fw-bold">Review Manuscript</h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="{{ url_for('reviewer.manuscript_review') }}" class="d-flex flex-column justify-content-center align-items-center fw-semibold" method="POST">
            <input type="hidden" name="id" value="{{ manuscript.id }}" required>
            <div class="w-100">
              <p class="fs-6 form-label fw-semibold">Are you sure want to review manuscript with title: <br/><span class="fw-semibold fs-5">{{ manuscript.title }}</span></p>
            </div>
            <button type="submit" class="btn btn-primary w-100 fw-bold mt-3 fw-bold">Review Manuscript</button>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary fw-bold" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

  <!-- Reject Manuscript Modal -->
  <div id="rejectManuscript" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title fw-bold">Reject Manuscript</h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="{{ url_for('reviewer.manuscript_reject') }}" class="d-flex flex-column justify-content-center align-items-center fw-semibold" method="POST">
            <input type="hidden" class="form-control" id="input-id" name="id" value="{{ manuscript.id }}" required>
            <div class="mb-2 w-100">
              <p class="fs-6 form-label fw-semibold">Please specify your mail messages!</p>
              <p class="fs-6 form-label fw-semibold">This message will be sent to the manuscript sender.</p>
            </div>
            <div class="mb-2 w-100">
              <label for="input-subject" class="fs-6 form-label fw-semibold">Subject</label>
              <input type="text" class="form-control" id="input-subject" name="subject" required>
            </div>
            <div class="mb-2 w-100">
              <label for="input-messages" class="fs-6 form-label">Messages</label>
              <textarea type="text" class="form-control" id="input-messages" name="messages" required></textarea>
            </div>
            <button type="submit" class="btn btn-danger w-100 fw-bold mt-3 fw-bold">Send Rejection Message</button>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary fw-bold" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

  <div class="col-12 col-md-11 d-flex flex-column align-items-center justify-content-center mt-3">
    <h5 class="fw-semibold align-self-start">PDF: </h5>
    <iframe class="col-12 py-2 px-md-0 vh-100" src="{{ url_for('static', filename='docs/uploads/' + manuscript.journal_path) }}#toolbar=0">
  </div>
</div>
{% endblock %}

app/templates/pages/reviewer/manuscript/review.html
{% extends "layout/app.html" %}

{% block title %} | Journal {% endblock %}

{% block content %}
<div class="ps-sm-3 pb-5">
  <h3 class="fw-bold my-3">Handled Manuscripts</h3>
  <div class="col-12 col-md-11 mb-4 d-flex flex-column flex-md-row align-items-center justify-content-between">
    <div class="col-12 col-md-7">
      <input id="searchManuscript" class="form-control" type="text" placeholder="Search Manuscript...">
    </div>
    <div class="col-12 col-md-4">
      <select id="filterManuscriptByStatus" class="form-select">
        <option selected>All</option>
        {% for status in statuses %}
        <option value="{{ status.id }}">{{ status.name }}</option>
        {% endfor %}
      </select>
    </div>
  </div>
  {% if manuscripts|length == 0 %}
  <div class="col-12 col-md-11 d-flex flex-column align-items-center justify-content-center">
    <img class="col-9 col-md-4 mt-5" src="{{ url_for('static', filename='images/nothing.svg') }}">
    <h4 class="fw-semibold mt-4">No Manuscript Handled</h4>
  </div>
  {% endif %}
  <div id="myManuscripts" class="col-12 col-md-11">
    {% for manuscript in manuscripts %}
    <div style="border-radius: 16px;" class="manuscript border border-1 px-3 py-2 my-3">
      <p id="title" class="fs-4 fw-bold mb-1">{{ manuscript.title }}</p>
      <div class="d-flex align-items-center flex-row flex-wrap">
        <p style="font-size: medium;" class="fw-semibold me-2 mb-0">Author: </p>
        {% for author in manuscript.author %}
        <p style="font-size: medium;" class="fw-semibold me-2 mb-0">
          [{{ loop.index0 + 1 }}]
          <span><a href="mailto:{{ author.email }}" class="mb-0 text-decoration-none">{{ author.name }}</a></span>
        </p>
        {% endfor %}
      </div>
      <p id="topic" style="font-size: medium;" class="fw-semibold me-2 mb-0">Status: <span class="{{ manuscript.journal_log.status.color }}">{{ manuscript.journal_log.status.name }}</span></span></p>
      <p style="font-size: medium;" class="fw-semibold me-2 mb-0">Last updated: <span class="text-secondary">{{ manuscript.journal_log.timestamp }}</span></p>
      <div class="d-flex align-items-center mt-2">
        <a href="{{ url_for('reviewer.manuscript_download', filename=manuscript.journal_path) }}" target="_blank" type="button" class="btn btn-sm fw-semibold me-2 ms-auto text-primary"><i class="bi bi-download"></i> Download File</a>
        <form action="{{ url_for('reviewer.manuscript_view_detail', id=manuscript.id) }}" method="POST">
          <input type="hidden" name="path" value="{{ request.endpoint }}">
          <input type="hidden" name="breadcrumb" value="Handled Manuscripts">
          <button type="submit" class="btn btn-primary btn-sm fw-semibold"><i class="bi bi-file-earmark"></i> View Detail</button>
        </form>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

{% block js %}
<script>
  $(document).ready(function() {
    $("#searchManuscript").on("keyup", function() {
      var search = $(this).val().toLowerCase();
      $("#myManuscripts div.manuscript").filter(function() {
        $(this).toggle($(this).find("#title").text().toLowerCase().indexOf(search) > -1)
      });
    });

    $("#filterManuscriptByStatus").on("change", function() {
      var filter = $(this).children("option:selected").text().toLowerCase();
      $("#myManuscripts div.manuscript").filter(function() {
        if(filter === 'all') {
          $(this).toggle(true);
        } else {
          $(this).toggle($(this).find("#topic span").text().toLowerCase() === filter);
        }
      });
    });
  });
</script>
{% endblock  %}

app/templates/pages/reviewer/manuscript/submission.html
{% extends "layout/app.html" %}

{% block title %} | Journal {% endblock %}

{% block content %}
<div class="ps-sm-3 pb-5">
  {% include "layout/flash.html" %}
  <h3 class="fw-bold my-3">New Manuscript Submissions</h3>
  <div class="col-12 col-md-11 mb-4 d-flex flex-column flex-md-row align-items-center justify-content-between">
    <div class="col-12 col-md-7">
      <input id="searchManuscript" class="form-control" type="text" placeholder="Search Manuscript...">
    </div>
    <div class="col-12 col-md-4">
      <select id="filterManuscriptByTopic" class="form-select">
        <option selected>All</option>
        {% for topic in topics %}
        <option value="{{ topic.id }}">{{ topic.name }}</option>
        {% endfor %}
      </select>
    </div>
  </div>
  {% if manuscripts|length == 0 %}
  <div class="col-12 col-md-11 d-flex flex-column align-items-center justify-content-center">
    <img class="col-9 col-md-4 mt-5" src="{{ url_for('static', filename='images/nothing.svg') }}">
    <h4 class="fw-semibold mt-4">No New Manuscripts Submitted</h4>
  </div>
  {% endif %}
  <div id="myManuscripts" class="col-12 col-md-11">
    {% for manuscript in manuscripts %}
    <div style="border-radius: 16px;" class="manuscript border border-1 px-3 py-2 my-3">
      <p id="title" class="fs-4 fw-bold mb-1">{{ manuscript.title }}</p>
      <div class="d-flex align-items-center flex-row flex-wrap">
        <p style="font-size: medium;" class="fw-semibold me-2 mb-0">Author: </p>
        {% for author in manuscript.author %}
        <p style="font-size: medium;" class="fw-semibold me-2 mb-0">
          [{{ loop.index0 + 1 }}]
          <span><a href="mailto:{{ author.email }}" class="mb-0 text-decoration-none">{{ author.name }}</a></span>
        </p>
        {% endfor %}
      </div>
      <p id="topic" style="font-size: medium;" class="fw-semibold me-2 mb-0">Topic: <span>{{ manuscript.topic.name }}</span></p>
      <p style="font-size: medium;" class="fw-semibold me-2 mb-0">Last updated: <span class="text-secondary">{{ manuscript.journal_log.timestamp }}</span></p>
      <div class="d-flex align-items-center mt-2">
        <a href="{{ url_for('reviewer.manuscript_download', filename=manuscript.journal_path) }}" target="_blank" type="button" class="btn btn-sm fw-semibold me-2 ms-auto text-primary"><i class="bi bi-download"></i> Download File</a>
        <form action="{{ url_for('reviewer.manuscript_view_detail', id=manuscript.id) }}" method="POST">
          <input type="hidden" name="path" value="{{ request.endpoint }}">
          <input type="hidden" name="breadcrumb" value="New Submissions">
          <button type="submit" class="btn btn-primary btn-sm fw-semibold me-2"><i class="bi bi-file-earmark"></i> View Detail</button>
        </form>
        <button class="btn btn-success btn-sm fw-semibold" data-bs-toggle="modal" data-bs-target="#reviewManuscript{{ manuscript.id }}"><i class="bi bi-search"></i> Review</button>
      </div>
    </div>
    
    <!-- Review Manuscript Modal -->
    <div id="reviewManuscript{{ manuscript.id }}" class="modal fade" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title fw-bold">Review Manuscript</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form action="{{ url_for('reviewer.manuscript_review') }}" class="d-flex flex-column justify-content-center align-items-center fw-semibold" method="POST">
              <input type="hidden" name="id" value="{{ manuscript.id }}" required>
              <div class="w-100">
                <p class="form-label fw-semibold">Are you sure want to review manuscript with title: <br/><span class="fw-semibold fs-5">{{ manuscript.title }}</span></p>
              </div>
              <button type="submit" class="btn btn-primary w-100 fw-bold mt-3 fw-bold">Review Manuscript</button>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary fw-bold" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

{% block js %}
<script>
  $(document).ready(function() {
    $("#searchManuscript").on("keyup", function() {
      var search = $(this).val().toLowerCase();
      $("#myManuscripts div.manuscript").filter(function() {
        $(this).toggle($(this).find("#title").text().toLowerCase().indexOf(search) > -1)
      });
    });

    $("#filterManuscriptByTopic").on("change", function() {
      var filter = $(this).children("option:selected").text().toLowerCase();
      $("#myManuscripts div.manuscript").filter(function() {
        if(filter === 'all') {
          $(this).toggle(true);
        } else {
          $(this).toggle($(this).find("#topic span").text().toLowerCase() === filter);
        }
      });
    });
  });
</script>
{% endblock  %}